// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8rEzGHwJMH-iw5xyqqE4Sm9EqxcLSME',
    appId: '1:957135752104:android:b6cfb20f3ca3849f80ab9d',
    messagingSenderId: '957135752104',
    projectId: 'my-chat-app-richi',
    storageBucket: 'my-chat-app-richi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wbbM5f9pM4_FBXkovlMZcJ_n-672K9g',
    appId: '1:957135752104:ios:65708f2eac8cf3ee80ab9d',
    messagingSenderId: '957135752104',
    projectId: 'my-chat-app-richi',
    storageBucket: 'my-chat-app-richi.appspot.com',
    iosClientId: '957135752104-99kmfohrm41ei69ojaaaosjpc8tq3brb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-wbbM5f9pM4_FBXkovlMZcJ_n-672K9g',
    appId: '1:957135752104:ios:65708f2eac8cf3ee80ab9d',
    messagingSenderId: '957135752104',
    projectId: 'my-chat-app-richi',
    storageBucket: 'my-chat-app-richi.appspot.com',
    iosClientId: '957135752104-99kmfohrm41ei69ojaaaosjpc8tq3brb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
